fastlane_version '2.53.1'
opt_out_usage

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles.'
  lane :certificates do
    match(app_identifier: 'tech.higia.*', type: 'development', readonly: false)
    match(app_identifier: 'tech.higia.*', type: 'appstore', readonly: false)
  end
  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/HigiaCoin.xcodeproj')
    gym(scheme: 'HigiaCoin', project: './ios/HigiaCoin.xcodeproj')
  end
  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    clean_build_artifacts
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/HigiaCoin.xcodeproj')
    push_to_git_remote
  end
end
