fastlane_version '2.53.1'
opt_out_usage

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles.'
  lane :certificates do
    match(git_url: 'git@github.com:bntzio/certificates.git', type: 'development')
    match(git_url: 'git@github.com:bntzio/certificates.git', type: 'appstore')
  end
  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/HigiaCoin.xcodeproj')
    gym(scheme: 'HigiaCoin', project: './ios/HigiaCoin.xcodeproj')
  end
  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    clean_build_artifacts
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/HigiaCoin.xcodeproj')
    push_to_git_remote
  end
end

platform :android do
  lane :beta do
    gradle(
      task: 'assembleRelease',
      project_dir: 'android/'
    )
  end
end
